"""initial schema

Revision ID: ca66b6a7e38e
Revises: 
Create Date: 2026-08-06 16:05:39.550092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca66b6a7e38e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Enum('rodzic', 'opiekun', 'trener', name='account_role'), nullable=False),
    sa.Column('plan', sa.Enum('free', 'paid', name='plan'), server_default='free', nullable=False),
    sa.Column('searches_used', sa.Integer(), server_default='0', nullable=False),
    sa.Column('lang', sa.String(length=2), server_default='pl', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('players',
    sa.Column('pzt_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('club', sa.String(), nullable=True),
    sa.Column('age_category', sa.Enum('SKRZATY', 'MLODZICY', 'KADECI', 'JUNIORZY', name='age_category'), nullable=True),
    sa.Column('gender', sa.Enum('BOYS', 'GIRLS', name='gender'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('pzt_id')
    )
    op.create_table('tournaments',
    sa.Column('guid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type_prefix', sa.String(), nullable=True),
    sa.Column('age_category', sa.Enum('SKRZATY', 'MLODZICY', 'KADECI', 'JUNIORZY', name='age_category'), nullable=False),
    sa.Column('ranga', sa.Integer(), nullable=True),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('wojewodztwo', sa.String(), nullable=True),
    sa.Column('entry_deadline', sa.DateTime(), nullable=True),
    sa.Column('withdrawal_deadline', sa.DateTime(), nullable=True),
    sa.Column('search_closes_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_table('account_players',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('player_pzt_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_pzt_id'], ['players.pzt_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id', 'player_pzt_id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tournament_guid', sa.String(), nullable=False),
    sa.Column('category_label', sa.String(), nullable=False),
    sa.Column('gender', sa.Enum('BOYS', 'GIRLS', name='gender'), nullable=False),
    sa.Column('play_type', sa.Enum('SINGLES', 'DOUBLES', name='play_type'), nullable=False),
    sa.Column('draw_format', sa.String(), nullable=True),
    sa.Column('is_doubles', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tournament_guid'], ['tournaments.guid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_guid', 'category_label', 'gender', 'play_type', name='uq_event_identity')
    )
    op.create_table('rankings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_pzt_id', sa.String(), nullable=False),
    sa.Column('ranking_list', sa.Enum('M12', 'W12', 'M14', 'W14', 'M16', 'W16', 'M18', 'W18', name='ranking_list'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_pzt_id'], ['players.pzt_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_pzt_id', 'ranking_list', 'year', 'month', name='uq_ranking_period')
    )
    op.create_table('searches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_pzt_id', sa.String(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('OPEN', 'REQUESTED', 'MATCHED', 'REJECTED', 'EXPIRED', name='search_state'), server_default='OPEN', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_pzt_id'], ['players.pzt_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_pzt_id', 'event_id', name='uq_search_player_event')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('search_a_id', sa.Integer(), nullable=False),
    sa.Column('search_b_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['search_a_id'], ['searches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['search_b_id'], ['searches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('search_a_id', name='uq_match_search_a'),
    sa.UniqueConstraint('search_b_id', name='uq_match_search_b')
    )
    op.create_table('requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_search_id', sa.Integer(), nullable=False),
    sa.Column('to_search_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'EXPIRED', 'CANCELLED', name='request_state'), server_default='PENDING', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_search_id'], ['searches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_search_id'], ['searches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_search_id', 'to_search_id', name='uq_request_pair')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requests')
    op.drop_table('matches')
    op.drop_table('searches')
    op.drop_table('rankings')
    op.drop_table('events')
    op.drop_table('account_players')
    op.drop_table('tournaments')
    op.drop_table('players')
    op.drop_table('accounts')
    # ### end Alembic commands ###

    # Alembic's autogenerated downgrade drops tables but not the Postgres
    # ENUM types backing them (they're not owned by any one table) —
    # without this, re-running upgrade after a downgrade fails with
    # "type already exists".
    for enum_name in (
        "account_role",
        "plan",
        "age_category",
        "gender",
        "play_type",
        "ranking_list",
        "search_state",
        "request_state",
    ):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
